# Generated by Django 3.2.11 on 2022-01-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workouts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsets',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
