# Generated by Django 3.2.11 on 2022-01-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workoutsets_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsets',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
